/**
 * Mango × QVAC — Shared styles
 * All StyleSheet.create calls in one place.
 */
import { StyleSheet, Platform } from 'react-native';

export const markdownStyles = StyleSheet.create({
  block: { marginBottom: 2 },
  codeBlock: { borderRadius: 8, padding: 10, marginVertical: 4, borderWidth: 1 },
  codeLang: { fontSize: 11, fontWeight: '600', marginBottom: 4, textTransform: 'uppercase' },
  codeText: { fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace', fontSize: 13, lineHeight: 18 },
  listItem: { flexDirection: 'row', gap: 6, paddingVertical: 1 },
  listBullet: { width: 14, fontSize: 14 },
  listNum: { width: 20, fontSize: 13, fontWeight: '600' },
  listText: { flex: 1, fontSize: 15, lineHeight: 22 },
});

export const styles = StyleSheet.create({
  root: { flex: 1 },
  flex: { flex: 1 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', height: 52, paddingHorizontal: 8, borderBottomWidth: 1 },
  headerBtn: { width: 60, alignItems: 'center', justifyContent: 'center', paddingVertical: 8 },
  headerBtnText: { fontSize: 16 },
  headerCenter: { flex: 1, alignItems: 'center' },
  headerTitle: { fontSize: 17, fontWeight: '600' },
  tabBar: { flexDirection: 'row', height: 64, borderTopWidth: 1, alignItems: 'center' },
  tab: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 6 },
  tabIcon: { fontSize: 20, opacity: 0.5 },
  tabActive: { opacity: 1 },
  tabLabel: { fontSize: 10, marginTop: 2 },
  tabActiveLabel: { fontWeight: '600' },
  tabNew: { width: 52, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', marginHorizontal: 16 },
  tabNewIcon: { fontSize: 24, fontWeight: '700', marginTop: -2 },
  chatScroll: { flex: 1 },
  chatContent: { paddingHorizontal: 12, paddingVertical: 12, paddingBottom: 8 },
  emptyChat: { alignItems: 'center', paddingTop: 80, paddingBottom: 40 },
  emptyChatIcon: { fontSize: 48, marginBottom: 16 },
  emptyChatTitle: { fontSize: 20, fontWeight: '600', marginBottom: 8 },
  emptyChatSub: { fontSize: 14, textAlign: 'center', paddingHorizontal: 40 },
  bubbleRow: { flexDirection: 'column', marginBottom: 12, gap: 2 },
  bubbleRowUser: { alignItems: 'flex-end' },
  bubbleRowAsst: { alignItems: 'flex-start' },
  bubbleAvatar: { fontSize: 18, marginBottom: 2 },
  bubble: { maxWidth: '78%', borderRadius: 18, paddingHorizontal: 14, paddingVertical: 10 },
  bubbleText: { fontSize: 15, lineHeight: 22 },
  toolCallItem: { borderRadius: 8, paddingHorizontal: 10, paddingVertical: 4, borderLeftWidth: 2, marginTop: 6 },
  toolCallText: { fontSize: 12, fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace' },
  composeBar: { flexDirection: 'row', alignItems: 'flex-end', gap: 8, paddingHorizontal: 12, paddingVertical: 8, borderTopWidth: 1 },
  composeInput: { flex: 1, borderRadius: 20, paddingHorizontal: 16, paddingVertical: 10, fontSize: 16, maxHeight: 120 },
  sendBtn: { width: 36, height: 36, borderRadius: 18, justifyContent: 'center', alignItems: 'center' },
  sendIcon: { fontSize: 18, fontWeight: '700' },
  composeFooter: { flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 4 },
  composeStatus: { fontSize: 11 },
  convList: { paddingHorizontal: 16, paddingVertical: 8 },
  convItem: { borderRadius: 14, padding: 16, marginBottom: 8, borderLeftWidth: 3 },
  convItemTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
  convTitle: { fontSize: 16, fontWeight: '600', flex: 1 },
  convDate: { fontSize: 12, marginLeft: 8 },
  convPreview: { fontSize: 13, lineHeight: 18 },
  emptyState: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 40 },
  emptyIcon: { fontSize: 56, marginBottom: 16 },
  emptyTitle: { fontSize: 28, fontWeight: '700', marginBottom: 8 },
  emptySub: { fontSize: 16, marginBottom: 24 },
  emptyHint: { fontSize: 14 },
  settingsContent: { paddingHorizontal: 16, paddingBottom: 40 },
  sectionTitle: { fontSize: 13, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.5, marginTop: 24, marginBottom: 8 },
  modelStatusCard: { borderRadius: 14, padding: 16, borderWidth: 1 },
  modelStatusRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  modelStatusIcon: { fontSize: 24 },
  modelStatusInfo: { flex: 1 },
  modelStatusName: { fontSize: 16, fontWeight: '600' },
  modelStatusDetail: { fontSize: 13, marginTop: 2 },
  unloadBtn: { marginTop: 10, paddingVertical: 8, borderRadius: 8, alignItems: 'center' },
  browseBtn: { marginTop: 8, paddingVertical: 12, alignItems: 'center' },
  browseText: { fontSize: 16, fontWeight: '600' },
  deviceCard: { borderRadius: 14, padding: 16, borderWidth: 1 },
  deviceRow: { fontSize: 14, marginBottom: 4 },
  aboutCard: { borderRadius: 14, padding: 20, borderWidth: 1 },
  aboutTitle: { fontSize: 18, fontWeight: '700', marginBottom: 8 },
  aboutText: { fontSize: 14, lineHeight: 22 },
  modelList: { paddingHorizontal: 16, paddingBottom: 40 },
  modelHint: { fontSize: 13, marginBottom: 16, marginTop: 8 },
  modelCard: { borderRadius: 14, padding: 16, marginBottom: 8, borderWidth: 1 },
  modelCardActive: { borderWidth: 2 },
  modelCardDisabled: { opacity: 0.5 },
  modelTop: { marginBottom: 10 },
  modelHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 4 },
  modelName: { fontSize: 16, fontWeight: '600', flex: 1 },
  modelBadge: { borderRadius: 6, paddingHorizontal: 8, paddingVertical: 2 },
  modelBadgeText: { fontSize: 11, fontWeight: '600' },
  modelDownBadge: { fontSize: 12 },
  modelDesc: { fontSize: 13 },
  modelFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  modelSize: { fontSize: 12 },
  modelActions: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  modelActionBtn: { paddingVertical: 4, paddingHorizontal: 8 },
  modelActive: { fontSize: 13, fontWeight: '600' },
  progressWrap: { marginVertical: 8 },
  progressBar: { height: 4, borderRadius: 2, overflow: 'hidden' },
  progressFill: { height: 4, borderRadius: 2 },
  progressText: { fontSize: 11, marginTop: 4 },
  micBtn: { width: 40, height: 40, borderRadius: 20, justifyContent: 'center', alignItems: 'center' },
  micIcon: { fontSize: 20 },
  micActive: { color: '#F87171' },
  ttsBtn: { marginTop: 4, alignSelf: 'flex-start', paddingHorizontal: 6, paddingVertical: 2 },
  ttsIcon: { fontSize: 14, opacity: 0.6 },
  whisperRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 10, paddingTop: 10, borderTopWidth: 1 },
  whisperInfo: { flex: 1, marginRight: 8 },
  whisperName: { fontSize: 14, fontWeight: '600' },
  whisperDesc: { fontSize: 12, marginTop: 2 },
  whisperActive: { fontSize: 12, fontWeight: '600' },
  whisperLoadBtn: { paddingVertical: 6, paddingHorizontal: 12, borderRadius: 8 },
  whisperLoadText: { fontSize: 13, fontWeight: '600' },
  whisperDLText: { fontSize: 12, fontWeight: '500' },
  menuPanel: { borderBottomWidth: 1, paddingHorizontal: 16, paddingVertical: 8 },
  menuItem: { paddingVertical: 10 },
  sysPromptPanel: { paddingHorizontal: 16, paddingVertical: 10, borderBottomWidth: 1 },
  sysPromptInput: { borderWidth: 1, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, fontSize: 14, minHeight: 60, maxHeight: 120 },
  editInput: { borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6, fontSize: 14, minHeight: 40, maxHeight: 100 },
  actionBtn: { paddingHorizontal: 12, paddingVertical: 4, borderRadius: 6 },
  msgActions: { flexDirection: 'row', gap: 10, alignItems: 'center', marginTop: 2, paddingHorizontal: 2 },
  msgActionText: { fontSize: 11 },
});
